name: Purge CDN cache

on:
  push:
    branches:
      - main

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: https://purge.jsdelivr.net/gh/zenfi/js-sdk-apps@main/dist/yotepresto/index.js
